function [out_bw, out_ia, cell_file_ids_bw, cell_file_ids_ia] = ALL_pixlecorr
% Get all *.mat files out of each stage folder out of each subject folder
% out of neurodata.

out_bw = [];
out_ia = [];

cell_file_ids_bw = cell(1);
cell_file_ids_ia = cell(1);

count_bw = 0;
count_ia = 0;

%names%get all the things in neurodata folder...
file_list_subjects = dir('C:\Users\ampm1\Desktop\oldmatlab\PCia\neurodata\');

%hard coded erasure of irrelevant directory folders
file_list_subjects(1:2) = [];

%exclude non-folders
file_names_subjects = {file_list_subjects([file_list_subjects(:).isdir])};

%number of folders
length_subjects = size(file_names_subjects{:},1);
%file_names_subjects{:}(1:length_subjects,1).name;

%iterate through subjects
for subject = 1:length_subjects
    
    %print update
    rat = file_names_subjects{:}(subject,1).name;
    
    %task folders
    task_folders = {'black_and_white' 'object_arrangement'};
    
    for task = 1:2
    
        %get all the *.mat in subject folder...
        file_list_sessions = dir(strcat('C:\Users\ampm1\Desktop\oldmatlab\PCia\neurodata\' , num2str(file_names_subjects{:}(subject,1).name),'\', task_folders{task}, '\*.mat'));

        %number of folders
        length_sessions = size(file_list_sessions,1);

        %iterate through sessions
        for session = 1:length_sessions

            day_file = file_list_sessions(session,1).name;
            %day = session
            
            %load session
            current_file = strcat('C:\Users\ampm1\Desktop\oldmatlab\PCia\neurodata\' ,num2str(rat),'\', task_folders{task},'\' ,num2str(day_file))
            load(strcat('C:\Users\ampm1\Desktop\oldmatlab\PCia\neurodata\' ,num2str(rat),'\', task_folders{task},'\' ,num2str(day_file)))
            
            %skip sessions without cells
            if isempty(clusters)
                continue
            else
                %constrain clusters
                %cluster_confidence = [3 4 5];
                %cluster_region = [1 2];
                %cluster_idx = ismember(clusters(:,2), cluster_confidence) & ismember(clusters(:,4), cluster_region);
                %clusters = clusters(cluster_idx, :);
                %skip sessions without cells
                if isempty(clusters)
                    continue
                end   
            end  
           
            sel_contexts = sort(context_ids); sel_contexts = sel_contexts([1 3 2 4]); %set to abab
            
            %INSERT FUNCTION HERE'
            if task == 1
                
                %size(clusters,1)
                
                for i = 1:size(clusters,1)
                    count_bw = count_bw+1;
                    cpc = pxl_corr(eptrials, clusters(i), sel_contexts);
                    close %close figure generated by heatmaps_trial'
                    out_bw = [out_bw; [cpc subject]];

                    cell_file_ids_bw{count_bw} = current_file;
                end
                
                %size(out_bw)

            elseif task == 2
                
                %check if all task contexts were visited
                visited_contexts = unique(eptrials(~isnan(eptrials(:,6)),6));
                if ~isequal(visited_contexts(1:4), [5 6 7 8]')
                    continue
                end
                
                
                for i = 1:size(clusters,1)
                    count_ia = count_ia+1;
                    [cpc, within_corrs] = pxl_corr(eptrials, clusters(i), sel_contexts);
                    close %close figure generated by heatmaps_trial
                    out_ia = [out_ia; [cpc within_corrs subject]];
                    cell_file_ids_ia{count_ia} = current_file;

                end
            end

        end
    
    end 
end

cell_file_ids_bw = cell_file_ids_bw';
cell_file_ids_ia = cell_file_ids_ia';

end

